language: elixir
branches:
  only:
    - "master"
cache:
  directories:
    - deps
    - _build
matrix:
  include:
    - elixir: 1.6.2
      otp_release: 20.2
    - elixir: 1.5.3
      otp_release: 20.2
    - elixir: 1.4.5
      otp_release: 19.3
      env: COVERALLS=true CREDO=true
    - elixir: 1.3.4
      otp_release: 19.3
    - elixir: 1.2.6
      otp_release: 18.3
    - elixir: 1.1.1
      otp_release: 18.3
dist: trusty
sudo: required
services:
  - docker
env:
  - COVERALLS=false
  - CREDO=false
before_script:
  - IP_IFACE=eth0 ./scripts/docker_up.sh
script:
  - MIX_ENV=test mix deps.compile
  - ./scripts/ci_tests.sh
