version: 2.1

orbs:
  elixir-orb: fresha/elixir-orb@0.2

workflows:
  version: 2
  ci:
    jobs:
      - elixir-orb/test:
          context: Hex
      - elixir-orb/static-check:
          dialyzer: true
          context: Hex
      - hold-for-dev-publish:
          type: approval
          requires:
            - elixir-orb/test
            - elixir-orb/static-check
          filters:
            branches:
              ignore:
                - master
      - elixir-orb/dev-publish:
          context: Hex
          requires:
            - hold-for-dev-publish
      - elixir-orb/deploy:
          context: Hex
          requires:
            - elixir-orb/test
            - elixir-orb/static-check
          filters:
            branches:
              only:
                - master